# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  # Здесь указывается имя вашего сервера PostgreSQL.
  # localhost - если он установлен локально
  host: localhost
  # Если вы используете докер, то укажите имя сервиса
  # host: db 
  username: ruby # Замените на имя пользователя PostgreSQL
  password: ruby # Замените на ваш пароль

development:
  <<: *default
  database: crypto_alert_service_dev # Замените на имя вашей базы данных для разработки

test:
  <<: *default
  database: crypto_alert_service_test # Замените на имя вашей базы данных для тестов

# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
# production:
#   primary:
#     <<: *default
#     database: storage/production.sqlite3
#   cache:
#     <<: *default
#     database: storage/production_cache.sqlite3
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *default
#     database: storage/production_queue.sqlite3
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *default
#     database: storage/production_cable.sqlite3
#     migrations_paths: db/cable_migrate
